import type { Nike } from "../types/index";

export const db : Nike[] = [
    {
        id: 1,
        name: 'Jordan 1 Low',
        image: 'nike1',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 299,
    },
    {
        id: 2,
        name: 'Black Air Max',
        image: 'nike2',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 349,
    },
    {
        id: 3,
        name: 'Nike Sneakers',
        image: 'nike3',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 329,
    },
    {
        id: 4,
        name: 'Runners',
        image: 'nike4',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 299,
    },
    {
        id: 5,
        name: 'Blue Sneakers',
        image: 'nike5',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 399,
    },
    {
        id: 6,
        name: 'Colorful',
        image: 'nike6',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 329,
    },
    {
        id: 7,
        name: 'Blue SB Woman',
        image: 'nike7',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 349,
    },
    {
        id: 8,
        name: 'Blue SB',
        image: 'nike8',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 379,
    },
    {
        id: 9,
        name: 'Nike Boots W',
        image: 'nike9',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 289,
    },
    {
        id: 10,
        name: 'Jordan 1 RB',
        image: 'nike10',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 349,
    },
    {
        id: 11,
        name: 'Low Dunks',
        image: 'nike11',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 399,
    },
    {
        id: 12,
        name: 'Brown Boots',
        image: 'nike12',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 379,
    },
  ]